{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85b9e014-638c-491f-bc1a-d35ceeb208fc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# daily_report.py\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "from datetime import datetime\n",
    "import os\n",
    "\n",
    "# --- Page Config ---\n",
    "st.set_page_config(page_title=\"Daily Delivery Report\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🧾 Daily Delivery Report\")\n",
    "st.caption(\"Automatically summarizes today’s product deliveries from uploaded PO sheets.\")\n",
    "\n",
    "# --- File Upload Section ---\n",
    "st.subheader(\"📦 Upload Today's PO Sheet\")\n",
    "\n",
    "uploaded_po = st.file_uploader(\"Upload your delivery PO sheet (CSV, XLSX, or PDF)\", type=[\"csv\", \"xlsx\", \"pdf\"])\n",
    "\n",
    "if uploaded_po is None:\n",
    "    st.info(\"Please upload a PO file to generate today's delivery report.\")\n",
    "    st.stop()\n",
    "\n",
    "# --- Read PO Data ---\n",
    "try:\n",
    "    if uploaded_po.name.lower().endswith(\".csv\"):\n",
    "        df = pd.read_csv(uploaded_po)\n",
    "    elif uploaded_po.name.lower().endswith(\".xlsx\"):\n",
    "        df = pd.read_excel(uploaded_po)\n",
    "    elif uploaded_po.name.lower().endswith(\".pdf\"):\n",
    "        from file_handler import read_po_file\n",
    "        df, _ = read_po_file(uploaded_po)\n",
    "    else:\n",
    "        st.error(\"Unsupported file format.\")\n",
    "        st.stop()\n",
    "except Exception as e:\n",
    "    st.error(f\"Error reading PO file: {e}\")\n",
    "    st.stop()\n",
    "\n",
    "# --- Clean Columns ---\n",
    "df.columns = [c.strip().title().replace(\" \", \"_\") for c in df.columns]\n",
    "expected_cols = [\"Sku\", \"Product\", \"Location\", \"Outstanding\"]\n",
    "\n",
    "for col in expected_cols:\n",
    "    if col not in df.columns:\n",
    "        df[col] = None\n",
    "\n",
    "df = df.dropna(subset=[\"Product\"])\n",
    "df[\"Outstanding\"] = pd.to_numeric(df[\"Outstanding\"], errors=\"coerce\").fillna(0)\n",
    "\n",
    "if df.empty:\n",
    "    st.warning(\"No valid delivery data found in this PO sheet.\")\n",
    "    st.stop()\n",
    "\n",
    "# --- Save for records ---\n",
    "today = datetime.now().strftime(\"%Y-%m-%d\")\n",
    "save_dir = \"data/delivery_reports\"\n",
    "os.makedirs(save_dir, exist_ok=True)\n",
    "csv_path = os.path.join(save_dir, f\"delivery_report_{today}.csv\")\n",
    "df.to_csv(csv_path, index=False)\n",
    "\n",
    "# --- Key Metrics ---\n",
    "st.markdown(\"## 📊 Delivery Summary\")\n",
    "\n",
    "total_products = len(df)\n",
    "total_delivered = int(df[\"Outstanding\"].sum())\n",
    "unique_locations = df[\"Location\"].nunique()\n",
    "\n",
    "col1, col2, col3 = st.columns(3)\n",
    "col1.metric(\"Delivered Products\", total_products)\n",
    "col2.metric(\"Total Units Delivered\", total_delivered)\n",
    "col3.metric(\"Locations Updated\", unique_locations)\n",
    "\n",
    "# --- Top Delivered Products ---\n",
    "st.markdown(\"### 🚀 Top Delivered Products\")\n",
    "top_delivered = df.sort_values(\"Outstanding\", ascending=False).head(10)\n",
    "\n",
    "fig1 = px.bar(\n",
    "    top_delivered,\n",
    "    x=\"Outstanding\",\n",
    "    y=\"Product\",\n",
    "    color=\"Outstanding\",\n",
    "    text=\"Outstanding\",\n",
    "    orientation=\"h\",  # Horizontal bars for readability\n",
    "    title=\"Top 10 Delivered Products Today\",\n",
    "    color_continuous_scale=\"teal\"\n",
    ")\n",
    "\n",
    "fig1.update_traces(textposition=\"outside\")\n",
    "fig1.update_layout(\n",
    "    height=500,\n",
    "    xaxis_title=\"Units Delivered\",\n",
    "    yaxis_title=\"Product Name\",\n",
    "    yaxis=dict(autorange=\"reversed\"),  # Top product at top\n",
    "    margin=dict(l=120, r=20, t=60, b=40),\n",
    "    title_x=0.3,\n",
    "    template=\"plotly_white\"\n",
    ")\n",
    "st.plotly_chart(fig1, use_container_width=True)\n",
    "\n",
    "# --- Deliveries by Location ---\n",
    "if \"Location\" in df.columns and df[\"Location\"].notna().any():\n",
    "    st.markdown(\"### 🏭 Deliveries by Location\")\n",
    "\n",
    "    location_summary = df.groupby(\"Location\", as_index=False)[\"Outstanding\"].sum().sort_values(\"Outstanding\", ascending=True)\n",
    "\n",
    "    fig2 = px.bar(\n",
    "        location_summary,\n",
    "        x=\"Outstanding\",\n",
    "        y=\"Location\",\n",
    "        color=\"Outstanding\",\n",
    "        text=\"Outstanding\",\n",
    "        orientation=\"h\",  # Horizontal layout for clarity (especially many locations)\n",
    "        color_continuous_scale=\"Blues\",\n",
    "        title=\"Delivered Units per Location\"\n",
    "    )\n",
    "\n",
    "    fig2.update_traces(textposition=\"outside\")\n",
    "    fig2.update_layout(\n",
    "        height=600,\n",
    "        xaxis_title=\"Units Delivered\",\n",
    "        yaxis_title=\"Location\",\n",
    "        margin=dict(l=120, r=20, t=60, b=40),\n",
    "        title_x=0.3,\n",
    "        template=\"plotly_white\"\n",
    "    )\n",
    "    st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "# --- Delivery Table ---\n",
    "st.markdown(\"### 📋 Delivery Breakdown\")\n",
    "st.dataframe(df[[\"Product\", \"Sku\", \"Location\", \"Outstanding\"]], use_container_width=True)\n",
    "\n",
    "# --- Download Report ---\n",
    "st.markdown(\"### 💾 Export Today's Report\")\n",
    "\n",
    "csv_export = df.to_csv(index=False).encode(\"utf-8\")\n",
    "st.download_button(\n",
    "    label=\"⬇️ Download Daily Delivery Report (CSV)\",\n",
    "    data=csv_export,\n",
    "    file_name=f\"daily_delivery_report_{today}.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "st.success(f\"✅ Daily report generated for {today}\")\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"Daily delivery summary auto-generated from uploaded PO sheet.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "barcode_demo",
   "language": "python",
   "name": "barcode_demo"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
